name: build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: mymindstorm/setup-emsdk@v7

    - name: "Build jansson wasm"
      run: |
        mkdir -p ${HOME}/opt
        wget https://digip.org/jansson/releases/jansson-2.13.tar.gz
        tar -xzf jansson-2.13.tar.gz
        cd jansson-2.13
        emconfigure ./configure --prefix=${HOME}/opt
        make
        make install
    
    - name: "Build libfec wasm"
      run: |
        mkdir -p ${HOME}/opt
        git clone https://github.com/quiet/libfec.git
        cd libfec
        emconfigure ./configure --prefix=${HOME}/opt
        sed -i 's/ldconfig//g' makefile
        make
        make install

    - name: "Build quiet-dsp wasm"
      run: |
        mkdir -p ${HOME}/opt
        git clone https://github.com/quiet/quiet-dsp.git
        cd quiet-dsp
        git checkout devel
        export EMCC_CFLAGS="-I${HOME}/opt/include -DLIBFEC_ENABLED=1"
        aclocal
        autoconf
        autoheader
        emconfigure ./configure --prefix=${HOME}/opt
        sed -i 's/ldconfig//g' makefile
        make
        make install
    
    - name: "Build quiet wasm"
      run: |
        mkdir -p ${HOME}/opt
        git clone https://github.com/quiet/quiet.git
        cd quiet

        mkdir -p build_js

        cd build_js
        emcmake cmake .. -DCMAKE_INSTALL_PREFIX:PATH=${HOME}/opt
        emmake make
        make install