name: build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: mymindstorm/setup-emsdk@v7

    - name: "Build jansson wasm"
      run: |
        mkdir -p ${HOME}/opt
        wget https://digip.org/jansson/releases/jansson-2.13.tar.gz
        tar -xzf jansson-2.13.tar.gz
        cd jansson-2.13
        emconfigure ./configure --prefix=${HOME}/opt
        make
        make install